export const APPCONFIGSTATE_INITIALIZE = 'APPCONFIGSTATE_INITIALIZE';
export const APPCONFIGSTATE_CHANGE_METER_LINE = 'APPCONFIGSTATE_CHANGE_METER_LINE';
export const APPCONFIGSTATE_TOGGLE_EQ_VEHICLE = 'APPCONFIGSTATE_TOGGLE_EQ_VEHICLE';
export const APPCONFIGSTATE_CALENDER_TYPE_SELECTOR = 'APPCONFIGSTATE_CALENDER_TYPE_SELECTOR';
export const APPCONFIGSTATE_DATE_SELECTOR = 'APPCONFIGSTATE_DATE_SELECTOR';

export const APPSECCONFIGSTATE_INITIALIZE = 'APPSECCONFIGSTATE_INITIALIZE';
export const APPSECCONFIGSTATE_CHANGE_THEME = 'APPSECCONFIGSTATE_CHANGE_THEME';

export const APPEQSTATE_INITIALIZE = 'APPEQSTATE_INITIALIZE';
export const APPEQSTATE_EQUIPMENT_ARRANGEMENT_TYPE = 'APPEQSTATE_EQUIPMENT_ARRANGEMENT_TYPE';
export const APPEQSTATE_SELECT_AREA_TYPE = 'APPEQSTATE_SELECT_AREA_TYPE';
export const APPEQSTATE_SELECT_SUB_AREA_TYPE = 'APPEQSTATE_SELECT_SUB_AREA_TYPE';

export const RESET_ALL_STATE = 'RESET_ALL_STATE';


